### ISSUE TITLE
Internal artifactory User & Pass

### ISSUE THREAD

**Issue by mgvazquez** [bsorrentino/artifactory-tools#1]
Hello Sorrentino ,
Sorry for the inconvenience, but had no way to communicate with you .
Be careful what commits to GitHub . I was looking for an Artifactory plugin, and reached to your repo. Reading it, I found that " ArtifactoryForgePluginTest.java " class has your username and password hardcoded into it.

Be careful what That (Y)

C'ya :)

**Comment by bsorrentino** [comment]
Thx for feedback

I'll take care next time
